# Generated by Django 4.2.4 on 2023-08-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_uploadedcontent_delete_uploadedimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontent',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadedcontent',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
